### ISSUE TITLE
プリセットの値が保存されない

### ISSUE THREAD

**Issue by mre1ght** [tigerscave/eight-eel-camera-viewer#14]
## 現状
・プリセット保存ボタンを押した時に、プリセットの値が保存されない。

## 理想
・各１〜３までのプリセット保存を押すと、localStorageに値が保存される。

## 解決方法
・リロードの時間を変更する。

**Comment by falconkun** [comment]
save_request関数を修正
- preset_requestに関数名を修正
- ip_addr,preset_numの引数をjsから取得
- request.getの引数にIPアドレスとプリセットの番号を代入
- JSからPythonのpreset_requestの関数を叩けるように修正
